In [4]:
import sys; 
sys.path.append('../../')
from DataPreparation.Ingestion.Ingestion import read_data
from DataPreparation.Preprocessing.Preprocessing import preprocess_data, encode_data

#### Ingestion

In [5]:
df = read_data(
    path='../../../DataFiles/house-prices-advanced-regression-techniques/')

#### Visualize columns

In [6]:
# print all non-numerical columns
categorical_cols = [col for col in df.columns if df[col].dtype not in [
    "int64", "float64"] ]
print("Num of categorical data colums:",len(categorical_cols))
print(categorical_cols)

Num of categorical data colums: 43
['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']

In [7]:
ordinal_cols = ["GarageQual", "GarageCond", "PoolQC", "ExterQual", "ExterCond", "BsmtQual", "BsmtCond", "BsmtExposure", "FireplaceQu",
                "HeatingQC", "KitchenQual", "BsmtFinType1", "BsmtFinType2", "Functional", "GarageFinish", "Fence", "PavedDrive"]

# Print unique values of ordinal columns.
for col in ordinal_cols:
    print(col, df[col].unique())

GarageQual ['TA' 'Fa' 'Gd' nan 'Ex' 'Po']
GarageCond ['TA' 'Fa' nan 'Gd' 'Po' 'Ex']
PoolQC [nan 'Ex' 'Fa' 'Gd']
ExterQual ['Gd' 'TA' 'Ex' 'Fa']
ExterCond ['TA' 'Gd' 'Fa' 'Po' 'Ex']
BsmtQual ['Gd' 'TA' 'Ex' nan 'Fa']
BsmtCond ['TA' 'Gd' nan 'Fa' 'Po']
BsmtExposure ['No' 'Gd' 'Mn' 'Av' nan]
FireplaceQu [nan 'TA' 'Gd' 'Fa' 'Ex' 'Po']
HeatingQC ['Ex' 'Gd' 'TA' 'Fa' 'Po']
KitchenQual ['Gd' 'TA' 'Ex' 'Fa']
BsmtFinType1 ['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' nan 'LwQ']
BsmtFinType2 ['Unf' 'BLQ' nan 'ALQ' 'Rec' 'LwQ' 'GLQ']
Functional ['Typ' 'Min1' 'Maj1' 'Min2' 'Mod' 'Maj2' 'Sev']
GarageFinish ['RFn' 'Unf' 'Fin' nan]
Fence [nan 'MnPrv' 'GdWo' 'GdPrv' 'MnWw']
PavedDrive ['Y' 'N' 'P']

#### Preprocessing

In [8]:
x_train, y_train, x_val, y_val = preprocess_data(df)

columns having only 2 unique values: 3
['Street', 'Utilities', 'CentralAir']
columns having only <=10 unique values: 33
['MSZoning', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']
columns having only <=10 unique values: 3
['Neighborhood', 'Exterior1st', 'Exterior2nd']

#### Then visualizing the results

In [9]:
x_train.describe()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,4275.000000,4275.000000,4275.000000,4275.000000,4275.000000,4275.000000,4275.000000,4275.000000,4275.000000,4275.000000,...,4275.000000,4275.000000,4275.000000,4275.0,4275.000000,4275.0,4275.0,4275.000000,4275.000000,4275.000000
mean,74.362573,63.575556,9232.525673,6.192281,5.586901,1973.556491,1989.528304,95.238596,437.039708,58.247251,...,107.958947,43.538713,22.637749,0.0,16.066199,0.0,0.0,6.233918,2007.829708,185769.386901
std,51.517878,24.895195,5812.525041,1.357827,1.090486,27.462610,13.282363,178.402444,456.447687,182.281891,...,135.913417,60.973439,61.197664,0.0,56.146610,0.0,0.0,2.664788,1.305833,87009.959465
min,20.000000,21.000000,1300.000000,3.000000,1.000000,1922.000000,1974.500000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,1.000000,2006.000000,37900.000000
25%,20.000000,50.000000,5251.500000,5.000000,5.000000,1957.000000,1974.500000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,5.000000,2007.000000,128000.000000
50%,60.000000,68.000000,8885.000000,6.000000,5.000000,1977.000000,1991.000000,0.000000,315.000000,0.000000,...,87.000000,20.000000,0.000000,0.0,0.000000,0.0,0.0,6.000000,2008.000000,167240.000000
75%,120.000000,75.000000,11764.000000,7.000000,6.000000,1999.000000,2004.000000,130.000000,722.000000,0.000000,...,168.000000,66.000000,0.000000,0.0,0.000000,0.0,0.0,8.000000,2009.000000,220000.000000
max,190.000000,156.500000,29285.125000,10.000000,9.000000,2009.000000,2010.000000,1140.000000,2609.750000,990.500000,...,837.500000,400.125000,450.375000,0.0,400.000000,0.0,0.0,12.000000,2010.000000,755000.000000

In [10]:
null_counts = x_train.isnull().sum()

# print the summary of null values for each column
null_counts[null_counts != 0]

Series([], dtype: int64)

In [11]:
x_val.describe()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,...,365.000000,365.000000,365.000000,365.0,365.000000,365.0,365.0,365.000000,365.000000,365.000000
mean,57.684932,69.750685,10014.117466,6.158904,5.539726,1972.843836,1990.136986,105.273973,462.663014,52.484932,...,100.408219,48.014041,24.043836,0.0,13.060274,0.0,0.0,6.520548,2007.827397,181965.164384
std,41.830334,18.666559,4560.496704,1.377591,1.085208,28.149429,13.394239,180.243155,439.762153,167.196093,...,129.137462,66.455739,64.155402,0.0,47.953809,0.0,0.0,2.688547,1.334379,79241.939456
min,20.000000,21.000000,1680.000000,3.000000,2.000000,1922.000000,1974.500000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,1.000000,2006.000000,34900.000000
25%,20.000000,60.000000,7795.000000,5.000000,5.000000,1953.000000,1974.500000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,5.000000,2007.000000,129900.000000
50%,50.000000,69.000000,9375.000000,6.000000,5.000000,1975.000000,1993.000000,0.000000,397.000000,0.000000,...,0.000000,26.000000,0.000000,0.0,0.000000,0.0,0.0,6.000000,2008.000000,162000.000000
75%,75.000000,79.000000,11526.000000,7.000000,6.000000,2000.000000,2003.000000,167.000000,762.000000,0.000000,...,180.000000,66.000000,0.000000,0.0,0.000000,0.0,0.0,8.000000,2009.000000,214000.000000
max,190.000000,149.000000,29285.125000,10.000000,9.000000,2010.000000,2010.000000,1140.000000,1767.000000,990.500000,...,736.000000,400.125000,386.000000,0.0,276.000000,0.0,0.0,12.000000,2010.000000,555000.000000

In [12]:
null_counts = x_val.isnull().sum()

# print the summary of null values for each column
null_counts[null_counts != 0]

Series([], dtype: int64)

In [13]:
print(y_train.value_counts(normalize=False))
# AAAAAAAAAAAAAAAAAAAAAAAAAAA Class imbalance AAAAAAAAAAAAAAAAAAAAAAAAAAA

Neighborhood
3     171
6     171
10    171
13    171
24    171
2     171
18    171
1     171
4     171
19    171
7     171
14    171
22    171
23    171
5     171
9     171
15    171
21    171
17    171
20    171
8     171
16    171
12    171
11    171
0     171
Name: count, dtype: int64