In [8]:
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns
from scipy.stats import ttest_ind

%matplotlib inline

## Q2. Is there a significant difference in the mean SalePrice between properties with and without a pool (PoolArea > 0 vs. PoolArea = 0)?

In [9]:
df = pd.read_csv(
    './../DataFiles/house-prices-advanced-regression-techniques/train.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [10]:
df_with_pool = df[df['PoolArea'] > 0]
df_without_pool = df[df['PoolArea'] == 0]

In [13]:
mean_with_pool = df_with_pool['SalePrice'].mean()
mean_without_pool = df_without_pool['SalePrice'].mean()

# get variance
var_with_pool = df_with_pool['SalePrice'].var()
var_without_pool = df_without_pool['SalePrice'].var()

print('Mean with pool: ', mean_with_pool)
print('Variance with pool: ', var_with_pool)

print('Mean without pool: ', mean_without_pool)
print('Variance without pool: ', var_without_pool)

Mean with pool:  288138.5714285714
Variance with pool:  42465607747.61905
Mean without pool:  180404.66345492084
Variance without pool:  6110372630.880462

In [14]:
ttest_ind(df_with_pool['SalePrice'], df_without_pool['SalePrice'], equal_var=False)

Ttest_indResult(statistic=1.3827137645434016, pvalue=0.21594886916569525)

Answer:
------------
When comparing means of the samples we found there may be a difference but when testing for statistical significance there is no significant difference in the mean SalePrice between properties with and without a pool.